### ISSUE TITLE
Schemas folder missing from PyPi

### ISSUE THREAD

**Issue by iannis-b** [FABallemand/ezGPX#11]
The Schemas folder is missing from the package on PyPi.

**Comment by FABallemand** [comment]
Thanks for opening this issue, I will fix it as soon as possible.
Please not that I do not guarantee (yet) the result of the methods checking the XML schema.
If you are interested in this feature please let me know I will also check if it works properly.

**Comment by FABallemand** [comment]
ezGPX version 0.1.12 should solve this issue.
